version: '3'

services:

    app:
        container_name: travel-planner
        build:
            context: .
            dockerfile: ./compose/local/Dockerfile
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        links:
            - "postgresql_trips:postgresql_trips"
        depends_on:
            - postgresql_trips

    postgresql_trips:
        container_name: postgresql_trips
        image: postgres:14
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./db/:/docker-entrypoint-initdb.d
            - pgdata:/var/lib/postgres/datadb

volumes:
    pgdata: 