version: '3'

services:

    app:
        container_name: travel-planner
        build:
            context: .
            dockerfile: ./compose/local/Dockerfile
        volumes:
            - .:/app
        ports:
            - "8000:8000"